title: Danielle Shelton
logo: /assets/images/may30.jpg
description: contact me @ dsheltonny@gmail.com or [linkedin](https://www.linkedin.com/in/daniellesheltonny/)
#show_downloads: true
theme: jekyll-theme-minimal
