title: Danielle Shelton
logo:
description: As a former Surveyor in the civil construction industry, I aim to utilize industry knowledge and work experience gained over 15 years helping create some of the largest infrastructure projects in NYC with an educational background in Mathematics (BS) and Data Science (MS) in my new career.
show_downloads: false
theme: jekyll-theme-minimal
